### ISSUE TITLE
Add built-in enum type adapter

### ISSUE THREAD

**Issue by shiraji** [gfx/Android-Orma#366]
Hi,

I'm wondering is there any discussion about having built-in enum type adapter like gson/moshi have.

https://github.com/google/gson/blob/44cad04a639b3a53f4205f93acda37b3f7d10871/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L790

https://github.com/square/moshi/blob/56ae2758bfbfd2875fcc2696013d28d3de9c8bf3/moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java#L215

Basically, it converts enum to String using its name. 

I'm currently using the static adapter like this in kotlin.

```kotlin
@StaticTypeAdapter(targetType = Enum::class, serializedType = String::class)
object EnumAdapter {
    @JvmStatic
    fun <T : Enum<T>> serialize(source: T): String {
        return source.name
    }

    @JvmStatic
    fun <T : Enum<T>> deserialize(serialized: String, type: Class<T>): T {
        return type.enumConstants.first { it.name == serialized }
    }
}
```

Do you think it feasible that Android Orma has the default enum built in?

**Comment by gfx** [comment]
Thank you for the suggestion. It is interesting and in fact, it is possible.

I don't like this idea because enum's names are not always the specification of the enum. If you don't  serialize an Enum member, you can change the name of the enum members. Otherwise, i.e.when you serialize an Enum member, you must not change the name because it might be stored in DB.

This is why I use [test/.../EnumDescription](https://github.com/gfx/Android-Orma/blob/master/library/src/test/java/com/github/gfx/android/orma/test/toolbox/EnumDescription.java) interface to serialize and deserialize enums in [test/.../EnumTypeAdapter](https://github.com/gfx/Android-Orma/blob/master/library/src/test/java/com/github/gfx/android/orma/test/type_adapter/EnumTypeAdapter.java). The "serializing" value is not a part of `Enum` interface so that you can change both the name of the enum and the order of the members. In addition, one knows which is serialized and which isn't just by searching the `implements` of `EnumDescription`.

**Comment by shiraji** [comment]
Ok, I agree with you. Thanks for taking your time!
